service: serverless-emailer

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  appName: serverless-emailer
  apiVersion: v1
  sendGridAPIKey:
    local: testkey 
    dev: ${ssm:/serverless-emailer/thirdparty/sendgrid/dev/apikey~true} # retrieve encrypted key store
    prod: prodkey #${ssm:/serverless-emailer/thirdparty/sendgrid/prod/apikey~true}
  mailgunAPIKey:
    local: testkey
    dev: ${ssm:/serverless-emailer/thirdparty/mailgun/dev/apikey~true}
    prod: prodkey #${ssm:/serverless-emailer/thirdparty/mailgun/prod/apikey~true}
  mailgunURL:
    local: "url"
    dev: "url"
    prod: "url"
  
provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    SENDGRID_URL: "https://api.sendgrid.com/v3/mail/send"
    SENDGRID_API_KEY: ${self:custom.sendGridAPIKey.${self:custom.stage}}
    MAILGUN_URL: ${self:custom.mailgunURL.${self:custom.stage}}
    MAILGUN_API_KEY: ${self:custom.mailgunAPIKey.${self:custom.stage}}
    METRICS_COMMAND_NAME: "EmailerAPICall"
    HYSTRIX_TIMEOUT: "20000"
    HYSTRIX_MAX_CONCURRENT_REQUESTS: "64"
    HYSTRIX_ERROR_THRESHOLD: "32"

  tags:
    appName: ${self:custom.appName}
    stage: ${self:custom.stage}
    owner: tony.truong

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  email:
    handler: bin/email
    events:
      - http:
          path: ${self:custom.apiVersion}/email/send
          method: post
          cors: true  
